maintainer        "Chamila de Alwis"
maintainer_email  "chamilad@wso2.com"
description       "Base recipe for all WSO2 Private PaaS Cartridges"
version           "0.1"
depends           "stratos_base"
